repository_type: pipeline

nf_core_version: 4.0.2

lint:
  files_unchanged:
    - assets/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_dark.png
    - .gitattributes
    - .gitignore
  nextflow_config: false # TMP
  schema_params: false # TMP
  multiqc_config:
    - report_comment
  merge_markers:
    - .pixi/envs
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-sampletracking_logo_light.png
    - docs/CONTRIBUTING.md
    - docs/images/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/download_pipeline.yml
  nf_test_content: false

template:
  org: nf-cmgg
  name: sampletracking
  description: CMGG Sampletracking workflow
  author: Matthias De Smet
  version: 1.0.2dev
  force: true
  outdir: .
  is_nfcore: false
