lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_light.png
    - docs/images/nf-core-sampletracking_logo_dark.png
    - .github/workflows/linting.yml
    - .gitignore
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
repository_type: pipeline
template:
  prefix: nf-cmgg
  skip:
    - igenomes
